default: 00 01 02 03 04

00:
	python $@*/main.py |& tee $$(echo $@*/)output.txt
01:
	python $@*/main.py |& tee $$(echo $@*/)output.txt
02:
	python $@*/main.py | tee $$(echo $@*/)output.txt
03:
	python $@*/main.py | tee $$(echo $@*/)output.txt
04:
	python $@*/main.py | tee $$(echo $@*/)output.txt
